### PR TITLE
DataStream updates

### PR DESCRIPTION
**Pull request by KellyStathis**
repos.json for testing:
```
      {
          "name": "DataStream",
          "url": "https://api.datacite.org/dois",
          "homepage_url": "https://datastream.org/",
          "thumbnail": "https://{{ web_hostname }}/discover/img/sources/datastream_80x80.png",
          "type": "datastream",
          "set": "wdgcf.datastream",
          "item_url_pattern": "https://datastream.org/dataset/%id%",
          "enabled": true
      }
```

### CODE REVIEW

**Comment by prairiewest** [comment]
Should we rename this repo type from "datastream" to "datacite"?

**Comment by KellyStathis** [comment]
Nope, it's still its own repo type (DataStreamRepository.py). We're getting the initial list of datasets from the DataCite API, but then we are using DataStream's own metadata records for the metadata (rather than the DataCite DOI metadata)

**Comment by prairiewest** [comment]
OK I see that in the item_url_pattern thanks. No other comments from me

**Comment by prairiewest** [comment]
.... about the code, that is. :)  But after doing a harvest, I notice that Datacite still has this item indexed, but it's been deleted from Datastream:

https://datastream.org/dataset/99612119-164a-456a-a30d-5fadacd90433

Not a problem, just curious.

**Comment by KellyStathis** [comment]
Yes, we marked as "deleted" because of the 404. I let the DataStream folks know about that DOI :)

**Pull request merged**
