### PR TITLE
DBInterface refactor

### PR DESCRIPTION
**Pull request by KellyStathis**
Refactors DBInterface to use new **update_related_metadata** function instead of repeating code for different metadata elements.

**Testing**
Because this overhauls some of the functions that write to the db, I documented specific test cases here: https://docs.google.com/spreadsheets/d/1cgkWC9ExQY7ojdbd1hXtrzWpz-iikjSb11PV9ZN6VoA/edit#gid=0

Includes:
- initial run for one of each repo type (sqlite and postgres)
- adding + deleting all metadata fields (sqlite only)

**Notes**
- I pulled in changes from branch RDM-4758_check_for_downloads first since that is the most recent work, and master isn't currently stable. I'm submitting this PR against RDM-4758_check_for_downloads so that you don't have to review Paul's changes a second time as part of this PR. Let me know if you'd prefer that I cancel this and re-submit it against master.
- In the scope of my testing, I noticed a handful of issues that are (probably) out of scope for this pull request, noted in FIXME comments for now.

### CODE REVIEW

**Review by prairiewest — COMMENTED** [review]
Tested in FRDR test. 3 errors were logged:

1. A 404 error that probably should delete our copy of the record instead of stopping the run:

2021-09-22 09:04:09,125 INFO *** Repo: City of Edmonton Open Data Portal, type: socrata, (last harvested: 3 weeks 22 hours 47 minutes 52 seconds ago)
2021-09-22 09:04:09,126 DEBUG This repo already exists in the database; updating
2021-09-22 09:04:16,326 INFO Found 2433 items in feed
2021-09-22 09:04:16,381 INFO Looking for stale records to update
2021-09-22 09:04:16,385 INFO Started processing for 100 records
2021-09-22 09:04:25,453 ERROR Updating record q87a-wy37 failed: 404 Client Error: Not Found
2021-09-22 09:04:25,454 ERROR Unable to delete related table rows for record q87a-wy37
2021-09-22 09:04:25,699 ERROR Aborting due to errors after 12 items updated in 9 seconds (1.3 items/sec)

2. Not sure why these errors appeared:

2021-09-22 09:09:26,595 INFO *** Repo: Données Québec, type: ckan, (last harvested: 3 weeks 22 hours 45 minutes 50 seconds ago)
2021-09-22 09:09:26,595 DEBUG This repo already exists in the database; updating
2021-09-22 09:09:27,761 INFO Done 1000 item headers after 1 second (789.2 items/sec)
2021-09-22 09:09:27,927 INFO Found 1217 items in feed
2021-09-22 09:09:27,985 INFO Looking for stale records to update
2021-09-22 09:09:27,988 INFO Started processing for 100 records
2021-09-22 09:09:32,344 ERROR Unable to delete related table rows for record esperance-de-vie-a-divers-ages-quebec-1931-2011
2021-09-22 09:09:40,643 ERROR Unable to delete related table rows for record evolution-de-la-part-de-lemploi-pour-certains-groupes-dage-quebec-1976-2010
2021-09-22 09:09:41,005 ERROR Unable to delete related table rows for record evolution-de-la-population-active-pour-certains-groupes-dage-en-milliers-quebec-1976-2010
2021-09-22 09:09:41,371 ERROR Unable to delete related table rows for record evolution-de-la-proportion-de-menages-qui-disposent-dun-vehicule-selon-lage-du-soutien-du-menag
2021-09-22 09:09:41,837 ERROR Unable to delete related table rows for record evolution-de-lage-moyen-de-la-prise-de-la-retraite-quebec-ontario-canada-1990-2011
2021-09-22 09:09:42,191 ERROR Unable to delete related table rows for record evolution-de-lemploi-personnes-de-tous-niveaux-de-scolarite-et-titulaires-dun-grade-u-2000-2011
2021-09-22 09:09:43,819 ERROR Unable to delete related table rows for record fb70c632427e4d08ab8da27f586f0d57_0
2021-09-22 09:09:44,288 ERROR Unable to delete related table rows for record fe1e81f09cac4089aed84424add0d65e_0
2021-09-22 09:10:11,654 ERROR Unable to delete related table rows for record individus-utilisant-internet-a-partir-de-nimporte-quel-endroit-ayant-commande-un-produit-o-2010
2021-09-22 09:10:19,465 ERROR Unable to delete related table rows for record la-bibliographie-du-quebec
2021-09-22 09:10:22,148 INFO Updated 100 items in 54 seconds (1.8 items/sec)

3. Similar errors:

2021-09-22 09:10:22,150 INFO *** Repo: Dryad, type: dryad, (last harvested: 3 weeks 22 hours 44 minutes 57 seconds ago)
2021-09-22 09:10:33,978 DEBUG This repo already exists in the database; updating
2021-09-22 09:11:07,959 INFO Found 876 items in feed
2021-09-22 09:11:13,632 INFO Looking for stale records to update
2021-09-22 09:11:13,754 INFO Started processing for 5000 records
2021-09-22 09:11:13,869 ERROR Unable to delete related table rows for record doi:10.5061/dryad.mkkwh70wg
2021-09-22 09:11:14,200 ERROR Unable to delete related table rows for record doi:10.5061/dryad.8157n
2021-09-22 09:11:14,521 ERROR Unable to delete related table rows for record doi:10.5061/dryad.8nm35

**Comment by KellyStathis** [comment]
1. It looks like this only aborts if the number of errors exceeds the value for "abort_after_numerrors" set in harvester.conf. What is this set to on test? It looks like it aborted after only 2 errors (I have this set to 50 by default locally).
2. So far, I'm not able to replicate the "Unable to delete related table rows " error locally when manipulating incoming metadata to force deletions, but I've updated that error logging to print more information. It's odd because the call to `self.delete_all_related_records(tablename, record['record_id'])` should be printing something too since it calls `delete_row_generic()`—not sure where else it could be failing.

**Comment by prairiewest** [comment]
OK that helped!  Here is an expanded error:

2021-09-22 10:16:25,595 ERROR delete_row_generic() failed with sqlstring "DELETE from records_x_subjects where record_id=? and language='fr'": column "language" does not exist
LINE 1: ...from records_x_subjects where record_id=11298 and language='...

**Comment by prairiewest** [comment]
Hang on, I'll push an update to this branch to address this

**Comment by KellyStathis** [comment]
I think I just fixed the last error you posted, but not sure if it fixes the earlier errors. The earlier ones were triggered by full record deletion, but the most recent one looks like it was probably triggered from the update_related_metadata() function.

**Comment by prairiewest** [comment]
I'm done. Tested in sqlite and postgres, no new errors I see now.

**Comment by KellyStathis** [comment]
Since the branch was merged, going to reopen and merge against master.

**Pull request closed without merging**
